using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace letterhead.Models
{
    public class EmailTemplate
    {
        public string RequestCreate(string name, string empcode, string approver)
        {
            var template = "<p><b>Dear " + approver + ",</b></p>"
            + "<p>The ELPAD (Electronic Letter Pad) create by " + name + "( " + empcode + " ).</p>"
            + "<p><b>Warm Regards</b></p>"
            //+ "<p style='font-size:15px;color:#adadad;'><b>Team HGI-ELpad</b></p>"
            //+ "<p style='font-size:15px;color:#adadad;'>H. G. Infra Engineering Limited</p>"
            //+ "<p style='font-size:9px;color:#adadad;'>III-Floor, Sheel Mohar Plaza</p>"
            //+ "<p style='font-size:9px;color:#adadad;'>A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan–302001</p>"
            //+ "<p><img src='https://employeehelpdesk.hginfra.com/Content/img/g1.png' style='height:30px;'/></p>"
            //+ "<p><a href='https://digitalletterhead.hginfra.com/ '>www.digitalletterhead.hginfra.com</a></p>"

            +"<table width='600' cellspacing='0' cellpadding='0' border='0' style='padding: 32px 0; font-size:13px;font-weight: 500; font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';>"
                +"<tbody>"
                    +"<tr>"
                        +"<td width='120'' style='vertical-align:top;padding:0 16px'>"
                            + "<a href='https://digitalletterhead.hginfra.com/' data-external='true'><img width='100%' style='border:none' src='https://employeehelpdesk.hginfra.com/Content/img/g1.png'></a>"
                        +"</td>"
                        +"<td style='border-left:solid #d4d4d4 1px' width='16'></td>"
                        +"<td style='vertical-align: top; text-align:left;color:#002060; text-align:left'> <span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'>Team HGI-ELpad </span>"
                           +"<span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'> H. G. Infra Engineering Limited</span>"
                            +"<br/>"
                          +"<p style='border-bottom: 1px solid black;width:300px;'></p>"
                          +"<p>Board: +91-141-4106040 / 41</p>"
                          +"<p>IIIrd Floor, Sheel Mohar Plaza, A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan – 302001</p>"
                          +"<a href='https://digitalletterhead.hginfra.com/'>www.digitalletterhead.hginfra.com</a>"
                            +"<br/>"
                        +"</td></td>"
                    +"</tr>"
                +"</tbody>"
            +"</table>"

            + "<p style='font-size:10px;color:#adadad;'>Disclaimer: The information contained herein (including any accompanying documents) is confidential and is intended solely"
+ "for the addressee(s). If you have erroneously received this message, please immediately delete it and notify the sender.Also, if"
+ "you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or taking any action in"
+ "reliance on the contents of this message or any accompanying document is strictly prohibited and is unlawful.The organization"
+ "is not responsible for any damage caused by a virus or alteration of the e - mail by a third party or otherwise.The contents of this"
+ "message may not necessarily represent the views or policies of H.G.Infra Engineering Limited.</p>";

           
            return template;
        }

        public string RequestSendSPV(string name, string empcode, string approver)
        {
            var template = "<p><b>Dear " + approver + ",</b></p>"
            + "<p>The ELPAD (Electronic Letter Pad) request has been generated by " + name + "( " + empcode + " ), kindly review and approve for further use.</p>"
             + "<p><a href='https://digitalletterhead.hginfra.com/Home/ApproveRequest/' data-external='true'>Click Here</a> To Approve</p>"
            + "<p><b>Warm Regards</b></p>"
            //+ "<p style='font-size:15px;color:#adadad;'><b>Team HGI-ELpad</b></p>"
            //+ "<p style='font-size:15px;color:#adadad;'>H. G. Infra Engineering Limited</p>"
            //+ "<p style='font-size:9px;color:#adadad;'>III-Floor, Sheel Mohar Plaza</p>"
            //+ "<p style='font-size:9px;color:#adadad;'>A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan–302001</p>"
            //+ "<p><img src='https://employeehelpdesk.hginfra.com/Content/img/g1.png' style='height:30px;'/></p>"
            //+ "<p><a href='https://digitalletterhead.hginfra.com/ '>www.digitalletterhead.hginfra.com</a></p>"

             + "<table width='600' cellspacing='0' cellpadding='0' border='0' style='padding: 32px 0; font-size:13px;font-weight: 500; font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';>"
                + "<tbody>"
                    + "<tr>"
                        + "<td width='120'' style='vertical-align:top;padding:0 16px'>"
                            + "<a href='https://digitalletterhead.hginfra.com/' data-external='true'><img width='100%' style='border:none' src='https://employeehelpdesk.hginfra.com/Content/img/g1.png'></a>"
                        + "</td>"
                        + "<td style='border-left:solid #d4d4d4 1px' width='16'></td>"
                        + "<td style='vertical-align: top; text-align:left;color:#002060; text-align:left'> <span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'>Team HGI-ELpad </span>"
                           + "<span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'> H. G. Infra Engineering Limited</span>"
                            + "<br/>"
                          + "<p style='border-bottom: 1px solid black;width:300px;'></p>"
                          + "<p>Board: +91-141-4106040 / 41</p>"
                          + "<p>IIIrd Floor, Sheel Mohar Plaza, A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan – 302001</p>"
                          + "<a href='https://digitalletterhead.hginfra.com/'>www.digitalletterhead.hginfra.com</a>"
                            + "<br/>"
                        + "</td></td>"
                    + "</tr>"
                + "</tbody>"
            + "</table>"


            + "<p style='font-size:10px;color:#adadad;'>Disclaimer: The information contained herein (including any accompanying documents) is confidential and is intended solely"
+ "for the addressee(s). If you have erroneously received this message, please immediately delete it and notify the sender.Also, if"
+ "you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or taking any action in"
+ "reliance on the contents of this message or any accompanying document is strictly prohibited and is unlawful.The organization"
+ "is not responsible for any damage caused by a virus or alteration of the e - mail by a third party or otherwise.The contents of this"
+ "message may not necessarily represent the views or policies of H.G.Infra Engineering Limited.</p>";
            return template;
        }





        public string RequestSend(string name, string empcode,string approver,int Lid)
        {
            var template = "<p><b>Dear " + approver + ",</b></p>"
            + "<p>The ELPAD (Electronic Letter Pad) request has been generated by " + name + "( "+ empcode+" ), kindly review and approve for further use.</p>"
             + "<p><a href='https://digitalletterhead.hginfra.com/Home/ApproveRequest/"+Lid+"' data-external='true'>Click Here</a> To Approve</p>"
             + "<p><a href='https://digitalletterhead.hginfra.com/Home/performaMail/" + Lid + "' data-external='true'>Click Here</a> To View</p>"
            + "<p><b>Warm Regards</b></p>"
            //+ "<p style='font-size:15px;color:#adadad;'><b>Team HGI-ELpad</b></p>"
            //+ "<p style='font-size:15px;color:#adadad;'>H. G. Infra Engineering Limited</p>"
            //+ "<p style='font-size:9px;color:#adadad;'>III-Floor, Sheel Mohar Plaza</p>"
            //+ "<p style='font-size:9px;color:#adadad;'>A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan–302001</p>"
            //+ "<p><img src='https://employeehelpdesk.hginfra.com/Content/img/g1.png' style='height:30px;'/></p>"
            //+ "<p><a href='https://digitalletterhead.hginfra.com/ '>www.digitalletterhead.hginfra.com</a></p>"

             + "<table width='600' cellspacing='0' cellpadding='0' border='0' style='padding: 32px 0; font-size:13px;font-weight: 500; font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';>"
                + "<tbody>"
                    + "<tr>"
                        + "<td width='120'' style='vertical-align:top;padding:0 16px'>"
                            + "<a href='https://digitalletterhead.hginfra.com/' data-external='true'><img width='100%' style='border:none' src='https://employeehelpdesk.hginfra.com/Content/img/g1.png'></a>"
                        + "</td>"
                        + "<td style='border-left:solid #d4d4d4 1px' width='16'></td>"
                        + "<td style='vertical-align: top; text-align:left;color:#002060; text-align:left'> <span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'>Team HGI-ELpad </span>"
                           + "<span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'> H. G. Infra Engineering Limited</span>"
                            + "<br/>"
                          + "<p style='border-bottom: 1px solid black;width:300px;'></p>"
                          + "<p>Board: +91-141-4106040 / 41</p>"
                          + "<p>IIIrd Floor, Sheel Mohar Plaza, A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan – 302001</p>"
                          + "<a href='https://digitalletterhead.hginfra.com/'>www.digitalletterhead.hginfra.com</a>"
                            + "<br/>"
                        + "</td></td>"
                    + "</tr>"
                + "</tbody>"
            + "</table>"


            + "<p style='font-size:10px;color:#adadad;'>Disclaimer: The information contained herein (including any accompanying documents) is confidential and is intended solely"
+ "for the addressee(s). If you have erroneously received this message, please immediately delete it and notify the sender.Also, if"
+ "you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or taking any action in"
+ "reliance on the contents of this message or any accompanying document is strictly prohibited and is unlawful.The organization"
+ "is not responsible for any damage caused by a virus or alteration of the e - mail by a third party or otherwise.The contents of this"
+ "message may not necessarily represent the views or policies of H.G.Infra Engineering Limited.</p>";
            return template;
        }

        public string RequestSendtoback(string name, string empcode, string approver)
        {
            var template = "<p><b>Dear " + name + "( " + empcode + " ),</b></p>"
            + "<p>The ELPAD (Electronic Letter Pad) request has been send back by " + approver + ",kindly login to HGI-ELpad portal for further process.</p>"
            + "<p><b>Warm Regards</b></p>"
  
             + "<table width='600' cellspacing='0' cellpadding='0' border='0' style='padding: 32px 0; font-size:13px;font-weight: 500; font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';>"
                + "<tbody>"
                    + "<tr>"
                        + "<td width='120'' style='vertical-align:top;padding:0 16px'>"
                            + "<a href='https://digitalletterhead.hginfra.com/' data-external='true'><img width='100%' style='border:none' src='https://employeehelpdesk.hginfra.com/Content/img/g1.png'></a>"
                        + "</td>"
                        + "<td style='border-left:solid #d4d4d4 1px' width='16'></td>"
                        + "<td style='vertical-align: top; text-align:left;color:#002060; text-align:left'> <span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'>Team HGI-ELpad </span>"
                           + "<span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'> H. G. Infra Engineering Limited</span>"
                            + "<br/>"
                          + "<p style='border-bottom: 1px solid black;width:300px;'></p>"
                          + "<p>Board: +91-141-4106040 / 41</p>"
                          + "<p>IIIrd Floor, Sheel Mohar Plaza, A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan – 302001</p>"
                          + "<a href='https://digitalletterhead.hginfra.com/'>www.digitalletterhead.hginfra.com</a>"
                            + "<br/>"
                        + "</td></td>"
                    + "</tr>"
                + "</tbody>"
            + "</table>"
            + "<p style='font-size:10px;color:#adadad;'>Disclaimer: The information contained herein (including any accompanying documents) is confidential and is intended solely"
+ "for the addressee(s). If you have erroneously received this message, please immediately delete it and notify the sender.Also, if"
+ "you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or taking any action in"
+ "reliance on the contents of this message or any accompanying document is strictly prohibited and is unlawful.The organization"
+ "is not responsible for any damage caused by a virus or alteration of the e - mail by a third party or otherwise.The contents of this"
+ "message may not necessarily represent the views or policies of H.G.Infra Engineering Limited.</p>";
            return template;
        }

        public string RequestReject(string name, string empcode, string approver)
        {
            var template = "<p><b>Dear " + name + "( " + empcode + " ),</b></p>"
            + "<p>The ELPAD (Electronic Letter Pad) request has been rejected by " + approver + ".</p>"
            + "<p><b>Warm Regards</b></p>"

             + "<table width='600' cellspacing='0' cellpadding='0' border='0' style='padding: 32px 0; font-size:13px;font-weight: 500; font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';>"
                + "<tbody>"
                    + "<tr>"
                        + "<td width='120'' style='vertical-align:top;padding:0 16px'>"
                            + "<a href='https://digitalletterhead.hginfra.com/' data-external='true'><img width='100%' style='border:none' src='https://employeehelpdesk.hginfra.com/Content/img/g1.png'></a>"
                        + "</td>"
                        + "<td style='border-left:solid #d4d4d4 1px' width='16'></td>"
                        + "<td style='vertical-align: top; text-align:left;color:#002060; text-align:left'> <span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'>Team HGI-ELpad </span>"
                           + "<span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'> H. G. Infra Engineering Limited</span>"
                            + "<br/>"
                          + "<p style='border-bottom: 1px solid black;width:300px;'></p>"
                          + "<p>Board: +91-141-4106040 / 41</p>"
                          + "<p>IIIrd Floor, Sheel Mohar Plaza, A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan – 302001</p>"
                          + "<a href='https://digitalletterhead.hginfra.com/'>www.digitalletterhead.hginfra.com</a>"
                            + "<br/>"
                        + "</td></td>"
                    + "</tr>"
                + "</tbody>"
            + "</table>"
            + "<p style='font-size:10px;color:#adadad;'>Disclaimer: The information contained herein (including any accompanying documents) is confidential and is intended solely"
+ "for the addressee(s). If you have erroneously received this message, please immediately delete it and notify the sender.Also, if"
+ "you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or taking any action in"
+ "reliance on the contents of this message or any accompanying document is strictly prohibited and is unlawful.The organization"
+ "is not responsible for any damage caused by a virus or alteration of the e - mail by a third party or otherwise.The contents of this"
+ "message may not necessarily represent the views or policies of H.G.Infra Engineering Limited.</p>";
            return template;
        }

        public string RequestApprove(string name, string empcode, string approver)
        {
            var template = "<p><b>Dear " + name + "( " + empcode + " ),</b></p>"
            + "<p>The ELPAD (Electronic Letter Pad) request has been approved by " + approver + ",kindly review and check for further use.</p>"
            + "<p><b>Warm Regards</b></p>"
            //+ "<p style='font-size:15px;color:#adadad;'><b>Team HGI-ELpad</b></p>"
            //+ "<p style='font-size:15px;color:#adadad;'>H. G. Infra Engineering Limited</p>"
            //+ "<p style='font-size:9px;color:#adadad;'>III-Floor, Sheel Mohar Plaza</p>"
            //+ "<p style='font-size:9px;color:#adadad;'>A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan–302001</p>"
            //+ "<p><img src='https://employeehelpdesk.hginfra.com/Content/img/g1.png' style='height:30px;'/></p>"
            //+ "<p><a href='www.hginfra.com'>www.hginfra.com</a></p>"
             + "<table width='600' cellspacing='0' cellpadding='0' border='0' style='padding: 32px 0; font-size:13px;font-weight: 500; font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';>"
                + "<tbody>"
                    + "<tr>"
                        + "<td width='120'' style='vertical-align:top;padding:0 16px'>"
                            + "<a href='https://digitalletterhead.hginfra.com/' data-external='true'><img width='100%' style='border:none' src='https://employeehelpdesk.hginfra.com/Content/img/g1.png'></a>"
                        + "</td>"
                        + "<td style='border-left:solid #d4d4d4 1px' width='16'></td>"
                        + "<td style='vertical-align: top; text-align:left;color:#002060; text-align:left'> <span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'>Team HGI-ELpad </span>"
                           + "<span style='display: block; padding-top: 20px; line-height:0px;color:#002060;font-size:16px; font-weight: bold;'> H. G. Infra Engineering Limited</span>"
                            + "<br/>"
                          + "<p style='border-bottom: 1px solid black;width:300px;'></p>"
                          + "<p>Board: +91-141-4106040 / 41</p>"
                          + "<p>IIIrd Floor, Sheel Mohar Plaza, A-1 Tilak Marg, C-Scheme, Jaipur, Rajasthan – 302001</p>"
                          + "<a href='https://digitalletterhead.hginfra.com/'>www.digitalletterhead.hginfra.com</a>"
                            + "<br/>"
                        + "</td></td>"
                    + "</tr>"
                + "</tbody>"
            + "</table>"
            + "<p style='font-size:10px;color:#adadad;'>Disclaimer: The information contained herein (including any accompanying documents) is confidential and is intended solely"
+ "for the addressee(s). If you have erroneously received this message, please immediately delete it and notify the sender.Also, if"
+ "you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or taking any action in"
+ "reliance on the contents of this message or any accompanying document is strictly prohibited and is unlawful.The organization"
+ "is not responsible for any damage caused by a virus or alteration of the e - mail by a third party or otherwise.The contents of this"
+ "message may not necessarily represent the views or policies of H.G.Infra Engineering Limited.</p>";
            return template;
        }
    }
}