//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterhead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatterRequest
    {
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string LATTERNO { get; set; }
        public Nullable<int> LetterType { get; set; }
        public string REMARK { get; set; }
        public string LatterData { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<int> CREATEBY { get; set; }
        public Nullable<System.DateTime> CRAETEDATE { get; set; }
    }
}
