//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterhead.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class letterheadEntities : DbContext
    {
        public letterheadEntities()
            : base("name=letterheadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mst_Role> Mst_Role { get; set; }
        public virtual DbSet<Mst104_DEPARTMENT> Mst104_DEPARTMENT { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<Mst_SITE> Mst_SITE { get; set; }
        public virtual DbSet<LetterCrateType> LetterCrateTypes { get; set; }
        public virtual DbSet<USERSIGN> USERSIGNs { get; set; }
        public virtual DbSet<usermanual> usermanuals { get; set; }
        public virtual DbSet<LatterRequest> LatterRequests { get; set; }
        public virtual DbSet<Letter_Log_Process> Letter_Log_Process { get; set; }
        public virtual DbSet<mst_status> mst_status { get; set; }
        public virtual DbSet<Mst_USER> Mst_USER { get; set; }
    }
}
