//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterhead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_USER
    {
        public int ID { get; set; }
        public string FULLNAME { get; set; }
        public string MOBILENO { get; set; }
        public string EMAILID { get; set; }
        public string EMPCODE { get; set; }
        public string USERNAME { get; set; }
        public string USERPWD { get; set; }
        public Nullable<int> DEPTID { get; set; }
        public Nullable<int> SITEID { get; set; }
        public Nullable<int> ROLEID { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<bool> CANLOGIN { get; set; }
        public Nullable<bool> OneTimeUser { get; set; }
        public Nullable<int> IsApprover { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<int> CREATEBY { get; set; }
        public Nullable<System.DateTime> CRAETEDATE { get; set; }
    }
}
