//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterhead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_SUBDEPARTMENT
    {
        public int ID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> CODE { get; set; }
        public string SubDEPARTMENT { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<int> CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
