//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace letterhead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSIGN
    {
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string SIGNTITLE { get; set; }
        public string SIGNIMAGE { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CRERATEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
